In [1]:
import pandas

In [2]:
sample_data = pandas.read_csv('sample-data.csv')

In [3]:
sample_data

,Rank,City,Population,Definition,Total area (km squared),Population density (/km),Country
0,1,Chongqing,"30,165,500",Municipality,"82,403",366,China
1,2,Shanghai,"24,183,300",Municipality,"6,340.5","3,814",China
2,3,Beijing,"21,707,000",Municipality,"16,411","1,267",China
3,4,Istanbul,"15,029,231",Metropolitan municipality,"5,196","2,893",Turkey
4,5,Karachi,"14,910,352",City,"3,780","3,944",Pakistan
5,6,Dhaka,"14,399,000",Capital city,337.54,"42,659",Bangladesh
6,7,Tokyo,"13,515,271",Capital city,626.99,"21,556",Japan
7,8,Moscow,"13,200,000",Federal city,"2,511","5,256",Russia
8,9,Guangzhou,"13,081,000",City(sub-provincial),"7,434","1,760",China
9,10,Shenzhen,"12,528,300",City(sub-provincial),"1,992","6,889",China
10,11,Mumbai,"12,442,373",City,437.71,"28,426",India
11,12,So Paulo,"12,038,000",Municipality,"1,081.05","11,199",Brazil
12,13,Kinshasa,"11,462,000",City province,473.73,"24,195",Democratic Republic of the Congo
13,14,Tianjin,"11,249,000",Municipality,"11,920",944,China
14,15,Lahore,"11,126,000",Metropolitan area,502.55,"22,139",Pakistan
15,16,Delhi,"11,034,555",Capital city,461.83,"23,893",India
16,17,Jakarta,"10,624,000",Special capital region,661.5,"16,060",Indonesia
17,18,Dongguan,"10,615,000",City,"2,460","4,315",China
18,19,Seoul,"9,806,000",Special city,605.25,"16,202",South Korea
19,20,Foshan,"9,279,000",City,"3,797","2,444",China
20,21,Chengdu,"9,012,000",City(sub-provincial),"14,312",630,China
21,22,Lima,"8,894,000",Capital city,"2,672","3,329",Peru
22,23,Mexico City,"8,918,653",Capital city,607.22,"14,616",Mexico
23,24,London,"8,825,001",Capital city,"1,572","5,614",United Kingdom
24,25,Tehran,"8,694,000",Capital city,574.13,"15,143",Iran
25,26,Bangalore,"8,443,675",City,709,"11,909",India
26,27,New York,"8,398,748",City,786.3,"10,681",United States
27,28,Shenyang,"8,106,171",City(sub-provincial),"12,980",625,China
28,29,Wuhan,"8,035,000",City(sub-provincial),"8,494",946,China
29,30,Bogot,"7,963,000",Capital District,428.26,"18,594",Colombia
...,...,...,...,...,...,...,...
56,57,Alexandria,"4,616,625",Governorate,"2,300","2,007",Egypt
57,58,Kolkata,"4,496,694",Municipal corporation,185,"24,306",India
58,59,Ankara,"4,470,800",Metropolitan municipality-province,"1,910.92","2,340",Turkey
59,60,Surat,"4,467,797",Municipal Corporation,336,"13,297",India
60,61,Giza,"4,239,988",Governorate,289.08,"14,667",Egypt
61,62,Zhengzhou,"4,122,087",City(sub-provincial),"1,015.66","4,059",China
62,63,Los Angeles,"3,976,322",Municipalitycity,"1,213.85","3,276",United States
63,64,New Taipei City,"3,954,929",Special municipality,"2,052.57","1,927",Taiwan
64,65,Cape Town,"3,740,026",Metropolitan municipality,"2,444.97","1,530",South Africa
65,66,Yokohama,"3,726,167",Designated city,437.49,"8,517",Japan
66,67,Berlin,"3,671,000",City state,891.75,"4,117",Germany
67,68,Busan,"3,590,000",Metropolitan city,347.49,"10,331",South Korea
68,69,Xiamen,"3,531,347",City(sub-provincial),"1,699","2,078",China
69,70,Jeddah,"3,456,259",City,"1,765","1,958",Saudi Arabia
70,71,Durban,"3,442,361",Metropolitan municipality,"2,291.31","1,502",South Africa
71,72,Kabul,"3,414,100",Municipality city,275,"12,415",Afghanistan
72,73,Casablanca,"3,359,818",Prefecture,230,"14,608",Morocco
73,74,Hefei,"3,352,076",City,838.52,"3,998",China
74,75,Pyongyang,"3,255,388",Direct-controlled municipality,"2,113","1,541",North Korea
75,76,Madrid,"3,207,247",Municipality city,605.77,"5,294",Spain
76,77,Faisalabad,"3,203,846",City district,214,"14,971",Pakistan
77,78,Ekurhuleni,"3,178,470",Metropolitan municipality,"1,975.31","1,609",South Africa
78,79,Nairobi,"3,138,369",Capital district,694.9,"4,829",Kenya
79,80,Zhongshan,"3,121,275",City,"1,783.67","1,750",China
80,81,Pune,"3,115,431",Municipal corporation,450.69,"6,913",India
81,82,Addis Ababa,"3,103,673",Metropolitan municipality-province,526.99,"5,889",Ethiopia
82,83,Jaipur,"3,073,350",Municipal corporation,485,"6,337",India
83,84,Buenos Aires,"3,054,300",Federal district,203,"15,046",Argentina
84,85,Wenzhou,"3,039,439",City,"1,187.88","2,559",China
85,86,Incheon,"3,002,645",Metropolitan city,328.55,"9,139",South Korea

In [29]:
def highlight_10k_and_over(value):
    styles = []
    
    for row in value:
        color = 'black'
        
        try:
            if isinstance(row, str):
                valueFloat = float(row.replace(',',''))
                if valueFloat >= 10000:
                    color = 'red'
        except ValueError:
            color = 'black'

        rowColor = 'color: {0}'.format(color)
        styles.append(rowColor)
    
    return styles

In [31]:
sample_data.style.apply(highlight_10k_and_over, subset=['Population density (/km)'])